CREATE DATABASE [Finantial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test', FILENAME = N'X:\Your\Location\Finantial.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Test_log', FILENAME = N'X:\Your\Location\Finantial_log.mdf' , SIZE = 1024KB , FILEGROWTH = 10%)

USE [FINANTIAL]
GO

/****** Object:  Table [dbo].[CATESTATUSPAGO]    Script Date: 17/07/2017 12:05:41 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATESTATUSPAGO](
	[IDCATESTATUSPAGO] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](100) NULL,
	[ACTIVO] [bit] NULL,
 CONSTRAINT [PK_CATESTATUSPAGO] PRIMARY KEY CLUSTERED 
(
	[IDCATESTATUSPAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [FINANTIAL]
GO

/****** Object:  Table [dbo].[CATFORMAPAGO]    Script Date: 17/07/2017 12:05:57 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATFORMAPAGO](
	[IDCATFORMAPAGO] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](100) NULL,
	[ACTIVO] [bit] NULL,
 CONSTRAINT [PK_CATFORMAPAGO] PRIMARY KEY CLUSTERED 
(
	[IDCATFORMAPAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [FINANTIAL]
GO

/****** Object:  Table [dbo].[CATTIPODOCUMENTO]    Script Date: 17/07/2017 12:06:13 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATTIPODOCUMENTO](
	[IDCATTIPODOCUMENTO] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](100) NULL,
	[ACTIVO] [bit] NULL,
 CONSTRAINT [PK_CATTIPODOCUMENTO] PRIMARY KEY CLUSTERED 
(
	[IDCATTIPODOCUMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO